### ISSUE TITLE
Depricated class NavigationToolbar2TkAgg causes Error

### ISSUE THREAD

**Issue by julvanu** [NeuromorphicProcessorProject/snn_toolbox#122]
Hi,

I tried to convert my ANN using the snntoolbox command (DEV version), though I received an **Import Error for the matplotlib class NavigationToolbar2TkAgg** (Error Traceback below) which is used in bin/gui/gui.py line 37. I googled it and found out that it is a **depricated class** and **should be replace by NavigationToolbar2Tk**, and tadaa, for that class the import works perfectly fine.

Could you please update that in the repo? Thank you! :)

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", l
ine 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\runpy.py", l
ine 87, in _run_code
    exec(code, run_globals)
  File "D:\PyCharm 2021.3.3\projects\Complex-YOLOv4-Pytorch\venv\Scripts\snntoolbox.exe\__main__.py", line 7, in <modul
e>
  File "D:\PyCharm 2021.3.3\projects\Complex-YOLOv4-Pytorch\venv\lib\site-packages\snntoolbox\bin\run.py", line 51, in 
main
    from snntoolbox.bin.gui import gui
  File "D:\PyCharm 2021.3.3\projects\Complex-YOLOv4-Pytorch\venv\lib\site-packages\snntoolbox\bin\gui\gui.py", line 37,
 in <module>
    from matplotlib.backends.backend_tkagg import NavigationToolbar2TkAgg
**ImportError: cannot import name 'NavigationToolbar2TkAgg' from 'matplotlib.backends.backend_tkagg' (D:\PyCharm 2021.3.3
\projects\Complex-YOLOv4-Pytorch\venv\lib\site-packages\matplotlib\backends\backend_tkagg.py)**

**Comment by rbodo** [comment]
Thanks for the fix!

Just a heads-up: As you can probably tell, the GUI has not been actively developed in the past few years, so you won't have all functionality.
