### ISSUE TITLE
I can not run Brian2 simulator successfully!

### ISSUE THREAD

**Issue by jackyfaster** [NeuromorphicProcessorProject/snn_toolbox#40]
Hi rboda:
First of all, thanks for your amazing snntoolbox.
when i run a model with brian2 simulator, i got the following errors,  

the following is the running model,
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=======================================
conv2d_1 (Conv2D)            (None, 2, 28, 28)         20        
_________________________________________________________________
activation_1 (Activation)    (None, 2, 28, 28)         0         
_________________________________________________________________
average_pooling2d_1 (Average (None, 2, 14, 14)         0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 2, 14, 14)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 392)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 512)               201216    
_________________________________________________________________
activation_2 (Activation)    (None, 512)               0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 512)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 10)                5130      
_________________________________________________________________
activation_3 (Activation)    (None, 10)                0         
=======================================
Total params: 206,366
Trainable params: 206,366
Non-trainable params: 0

when i use python version 3.5.4 , got the following error;
[other module version information: Brian2-2.1.3.1   Keras-2.1.3  tensorflow(cpu) - 1.8.0]

Starting new simulation...

Current accuracy of batch:
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: C:\Users\ADMINI~1\AppData\Local\Temp\brian_debug_t5eeqquz.log  Additionally, you can also include a copy of the script that was run, available at: C:\Users\ADMINI~1\AppData\Local\Temp\brian_script_k7gc_dhm.py Thanks! [brian2]
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\envs\py354_snntoolbox\lib\site-packages\brian2\core\network.py", line 841, in before_run
    obj.before_run(run_namespace)
  File "C:\Users\Administrator\Anaconda3\envs\py354_snntoolbox\lib\site-packages\brian2\groups\group.py", line 1093, in before_run
    self.update_abstract_code(run_namespace=run_namespace)
  File "C:\Users\Administrator\Anaconda3\envs\py354_snntoolbox\lib\site-packages\brian2\groups\neurongroup.py", line 267, in update_abstract_code
    if not is_boolean_expression(code, variables):
  File "C:\Users\Administrator\Anaconda3\envs\py354_snntoolbox\lib\site-packages\brian2\parsing\expressions.py", line 64, in is_boolean_expression
    mod = ast.parse(expr, mode='eval')
  File "C:\Users\Administrator\Anaconda3\envs\py354_snntoolbox\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    v = v_reset
      ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Pycharm_workspace/snn_toolbox-master_two/snntoolbox/bin/run.py", line 66, in <module>
    main()
  File "D:/Pycharm_workspace/snn_toolbox-master_two/snntoolbox/bin/run.py", line 51, in main
    test_full(config)
  File "D:\Pycharm_workspace\snn_toolbox-master_two\snntoolbox\bin\utils.py", line 131, in test_full
    results = run(spiking_model, **testset)
  File "D:\Pycharm_workspace\snn_toolbox-master_two\snntoolbox\bin\utils.py", line 204, in wrapper
    results.append(run_single(snn, **testset))
  File "D:\Pycharm_workspace\snn_toolbox-master_two\snntoolbox\bin\utils.py", line 128, in run
    return snn.run(**test_set)
  File "D:\Pycharm_workspace\snn_toolbox-master_two\snntoolbox\simulation\utils.py", line 609, in run
    output_b_l_t = self.simulate(**data_batch_kwargs)
  File "D:\Pycharm_workspace\snn_toolbox-master_two\snntoolbox\simulation\target_simulators\brian2_target_sim.py", line 188, in simulate
    report='stdout', report_period=10*self.sim.ms)
  File "C:\Users\Administrator\Anaconda3\envs\py354_snntoolbox\lib\site-packages\brian2\core\base.py", line 278, in device_override_decorated_function
    return func(*args, **kwds)
  File "C:\Users\Administrator\Anaconda3\envs\py354_snntoolbox\lib\site-packages\brian2\units\fundamentalunits.py", line 2375, in new_f
    result = f(*args, **kwds)
  File "C:\Users\Administrator\Anaconda3\envs\py354_snntoolbox\lib\site-packages\brian2\core\network.py", line 951, in run
    self.before_run(namespace)
  File "C:\Users\Administrator\Anaconda3\envs\py354_snntoolbox\lib\site-packages\brian2\core\base.py", line 278, in device_override_decorated_function
    return func(*args, **kwds)
  File "C:\Users\Administrator\Anaconda3\envs\py354_snntoolbox\lib\site-packages\brian2\core\network.py", line 843, in before_run
    raise brian_object_exception("An error occurred when preparing an object.", obj, ex)
  File "<string>", line None
brian2.core.base.BrianObjectException: <no detail available>

when i use python version 3.6.5 , got the following error;
[other module version information: Brian2-2.0.1   Keras-2.1.6  tensorflow(cpu) - 1.8.0]

Starting new simulation...

Current accuracy of batch:
Starting simulation at t=0. s for a duration of 10. ms
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: C:\Users\ADMINI~1\AppData\Local\Temp\brian_debug_w4v38fbm.log  Additionally, you can also include a copy of the script that was run, available at: C:\Users\ADMINI~1\AppData\Local\Temp\brian_script_rs733m8u.py Thanks! [brian2]
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\envs\snntoolboox_play\lib\site-packages\brian2\codegen\runtime\numpy_rt\numpy_rt.py", line 122, in run
    exec(self.compiled_code, self.namespace)
  File "(string)", line 16, in <module>
NameError: name 'v' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Pycharm_workspace/snn_toolbox-master_two/snntoolbox/bin/run.py", line 66, in <module>
    main()
  File "D:/Pycharm_workspace/snn_toolbox-master_two/snntoolbox/bin/run.py", line 51, in main
    test_full(config)
  File "D:\Pycharm_workspace\snn_toolbox-master_two\snntoolbox\bin\utils.py", line 131, in test_full
    results = run(spiking_model, **testset)
  File "D:\Pycharm_workspace\snn_toolbox-master_two\snntoolbox\bin\utils.py", line 204, in wrapper
    results.append(run_single(snn, **testset))
  File "D:\Pycharm_workspace\snn_toolbox-master_two\snntoolbox\bin\utils.py", line 128, in run
    return snn.run(**test_set)
  File "D:\Pycharm_workspace\snn_toolbox-master_two\snntoolbox\simulation\utils.py", line 609, in run
    output_b_l_t = self.simulate(**data_batch_kwargs)
  File "D:\Pycharm_workspace\snn_toolbox-master_two\snntoolbox\simulation\target_simulators\brian2_target_sim.py", line 188, in simulate
    report='stdout', report_period=10*self.sim.ms)
  File "C:\Users\Administrator\Anaconda3\envs\snntoolboox_play\lib\site-packages\brian2\core\base.py", line 278, in device_override_decorated_function
    return func(*args, **kwds)
  File "C:\Users\Administrator\Anaconda3\envs\snntoolboox_play\lib\site-packages\brian2\units\fundamentalunits.py", line 2428, in new_f
    result = f(*args, **kwds)
  File "C:\Users\Administrator\Anaconda3\envs\snntoolboox_play\lib\site-packages\brian2\core\network.py", line 842, in run
    obj.run()
  File "C:\Users\Administrator\Anaconda3\envs\snntoolboox_play\lib\site-packages\brian2\core\base.py", line 181, in run
    codeobj()
  File "C:\Users\Administrator\Anaconda3\envs\snntoolboox_play\lib\site-packages\brian2\codegen\codeobject.py", line 98, in __call__
    return self.run()
  File "C:\Users\Administrator\Anaconda3\envs\snntoolboox_play\lib\site-packages\brian2\codegen\runtime\numpy_rt\numpy_rt.py", line 131, in run
    raise brian_object_exception(message, self.owner, exc)
brian2.core.base.BrianObjectException: Original error and traceback:
Traceback (most recent call last):
  File "C:\Users\Administrator\Anaconda3\envs\snntoolboox_play\lib\site-packages\brian2\codegen\runtime\numpy_rt\numpy_rt.py", line 122, in run
    exec(self.compiled_code, self.namespace)
  File "(string)", line 16, in <module>
NameError: name 'v' is not defined

Error encountered with object named "synapses".
Object was created here (most recent call only, full details in debug log):
  File "D:\Pycharm_workspace\snn_toolbox-master_two\snntoolbox\simulation\target_simulators\brian2_target_sim.py", line 103, in add_layer
    dt=self._dt*self.sim.ms))

An exception occured during the execution of code object synapses_pre_codeobject.
The error was raised in the following line:
    v += w
 NameError: name 'v' is not defined
(See above for original error message and traceback.)

Process finished with exit code 1

Could you kindly help me to find the reason? I am looking for your reply.

Yu

**Comment by rbodo** [comment]
@jackyfaster Please close if this pull-request fixed the issue.

**Comment by jackyfaster** [comment]
@rbodo hi,

thanks a lot for your reply , but i am not also successfully to run brian2.
 first of all, i changed some modules version, Keras to 2.1.3;  brian2 to 2.1.3.1;  numpy to 1.14.5; tensorflow to 1.8.0;  python to 3.5.4.
 I used the keyword arguments in following test

    self.layers.append(self.sim.NeuronGroup(
            np.prod(layer.output_shape[1:]), model=self.eqs, method='linear', 
            threshold=self.threshold,
            reset=self.v_reset, [dt=self._dt*self.sim.ms))

when I set self.eqs = 'v = 0 : 1' , i got the following error:
////////////////////////////////////////////////////////////////////////
    SyntaxError: Illegal line 'v+=w' in abstract code. Cannot write to subexpression 'v'.
//////////////////////////////////////////////////////////////////////

when i set self.eqs = 'v = : 1' , i  got another error as the following:
//////////////////////////////////////////////////////////////
    brian2.equations.equations.EquationError: Parsing failed: 
v = : 1
^
Expected end of text, found 'v'  (at char 0), (line:1, col:1)
//////////////////////////////////////////////////////////

**Comment by rbodo** [comment]
I believe the correct equation is
`self.eqs = 'v : 1'`

**Comment by jackyfaster** [comment]
Great ,it woks, thanks !
