### ISSUE TITLE
Unable to run keras example of Lenet5

### ISSUE THREAD

**Issue by theUnspecified** [NeuromorphicProcessorProject/snn_toolbox#42]
While trying to run keras example of lenet5 this error appears

OS: windows 10
tensorflow 1.4.0 (with CUDA)
keras 2.1.2

Scale factor: 1.00.
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\snntoolbox.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\snntoolbox\bin\run.py", line 50, in main
    test_full(config)
  File "c:\programdata\anaconda3\lib\site-packages\snntoolbox\bin\utils.py", line 95, in test_full
    normalize_parameters(parsed_model, config, **normset)
  File "c:\programdata\anaconda3\lib\site-packages\snntoolbox\conversion\utils.py", line 151, in normalize_parameters
    input_layer = layer._inbound_nodes[0].inbound_layers[0].name
AttributeError: 'Conv2D' object has no attribute '_inbound_nodes'

**Comment by rbodo** [comment]
Can you replace the offending line with `input_layer = model.layers[0].name`?

This should hopefully solve it. Will try to test and submit fix soon.

**Comment by rbodo** [comment]
Solved in release 0.3.1.
