### ISSUE TITLE
mnist_keras_nest example BadProperty 'iaf_psc_exp_ps'

### ISSUE THREAD

**Issue by dizcza** [NeuromorphicProcessorProject/snn_toolbox#52]
Running `mnist_keras_nest.py` example with NEST v2.18 throws an exception

```
Initializing nest simulator...

CSAConnector: libneurosim support not available in NEST.
Falling back on PyNN's default CSAConnector.
Please re-compile NEST using --with-libneurosim=PATH
/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/PyNN-0.9.5.dev0-py3.7.egg/pyNN/nest/__init__.py:53: UserWarning:Unable to install NEST extensions. Certain models may not be available.
/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/nest/lib/hl_api_helper.py:127: UserWarning:
ResetNetwork is deprecated and will be removed in NEST 3.0.
Loading data set from '.npz' files in /home/dizcza/PycharmProjects/other/snn_toolbox/temp/1575220683.8345785.

Evaluating input model on 5 samples...
Top-1 accuracy: 100.00%
Top-5 accuracy: 100.00%

Parsing input model...
Skipping layer InputLayer.
Parsing layer Conv2D.
Using activation relu.
Parsing layer Conv2D.
Using activation relu.
Parsing layer AveragePooling2D.
Parsing layer Conv2D.
Using activation relu.
Parsing layer Flatten.
Skipping layer Dropout.
Parsing layer Dense.
Using activation softmax.

Building parsed model...

Compiling parsed model...

Normalizing parameters...
Using 6000 samples for normalization.
INFO: Need ['0.06', '0.08', '0.00', '0.00'] GB for layer activations.
May have to reduce size of data set used for normalization.
Calculating activations of layer 00Conv2D_12x12x16 ...
Writing activations to disk...
Scale factor: 2.31.
Calculating activations of layer 01Conv2D_10x10x32 ...
Writing activations to disk...
Scale factor: 6.17.
Calculating activations of layer 03Conv2D_5x5x8 ...
Writing activations to disk...
Scale factor: 11.85.
Calculating activations of layer 05Dense_10 ...
Writing activations to disk...
Scale factor: 1.00.
Using scale factor 1.00 for softmax layer.

Evaluating parsed model on 5 samples...
Top-1 accuracy: 100.00%
Top-5 accuracy: 100.00%

Building spiking model...
Building layer: 00Conv2D_12x12x16
Traceback (most recent call last):
  File "examples/mnist_keras_nest.py", line 149, in <module>
    main(config_filepath)
  File "/home/dizcza/PycharmProjects/other/snn_toolbox/snntoolbox/bin/run.py", line 31, in main
    run_pipeline(config)
  File "/home/dizcza/PycharmProjects/other/snn_toolbox/snntoolbox/bin/utils.py", line 129, in run_pipeline
    spiking_model.build(parsed_model, **testset)
  File "/home/dizcza/PycharmProjects/other/snn_toolbox/snntoolbox/simulation/utils.py", line 436, in build
    self.add_layer(layer)
  File "/home/dizcza/PycharmProjects/other/snn_toolbox/snntoolbox/simulation/target_simulators/pyNN_target_sim.py", line 85, in add_layer
    self.sim.IF_curr_exp, self.cellparams, label=layer.name))
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/PyNN-0.9.5.dev0-py3.7.egg/pyNN/nest/populations.py", line 114, in __init__
    super(Population, self).__init__(size, cellclass, cellparams, structure, initial_values, label)
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/PyNN-0.9.5.dev0-py3.7.egg/pyNN/common/populations.py", line 671, in __init__
    self._create_cells()
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/PyNN-0.9.5.dev0-py3.7.egg/pyNN/nest/populations.py", line 135, in _create_cells
    self.all_cells = nest.Create(nest_model, self.size, params=params)
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/nest/ll_api.py", line 246, in stack_checker_func
    return f(*args, **kwargs)
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/nest/lib/hl_api_nodes.py", line 80, in Create
    sr(cmd)
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/nest/ll_api.py", line 132, in catching_sli_run
    raise exceptionCls(commandname, message)
nest.ll_api.BadProperty: ("BadProperty in SetDefaults_l_D: Setting status of model 'iaf_psc_exp_ps': Refractory time must be at least one time step.", 'BadProperty', <SLILiteral: SetDefaults_l_D>, ": Setting status of model 'iaf_psc_exp_ps': Refractory time must be at least one time step.")
```

NEST v2.18, conda-forge built. The same with `libneurosim` compiled.
pyNN is installed as suggested [here](https://www.nest-simulator.org/mailinglist/hyperkitty/list/users@nest-simulator.org/thread/VAZMC73JMOFUD7YZVFHYBMM5CXE7CZYK) (otherwise, it does not work at all)

**Comment by rbodo** [comment]
Based on the error message, please add the following to the config dict:

```
config['cell'] = {
    'tau_refrac': 1               # Refractory period must be at least one time step.
}
```

Let me know if that solves the issue (I have no access to a nest installation at the moment).

**Comment by dizcza** [comment]
Then I got

```
Building spiking model...
Building layer: 00Conv2D_12x12x16
NEST does not allow setting an initial value for isyn_exc
NEST does not allow setting an initial value for isyn_inh
Transposing kernels.
/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/keras/utils/conv_utils.py:82: FutureWarning:Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
................
Traceback (most recent call last):
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/PyNN-0.9.5.dev0-py3.7.egg/pyNN/nest/projections.py", line 173, in _convergent_connect
    syn_dict)
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/nest/ll_api.py", line 246, in stack_checker_func
    return f(*args, **kwargs)
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/nest/lib/hl_api_connections.py", line 362, in Connect
    sr('Connect')
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/nest/ll_api.py", line 132, in catching_sli_run
    raise exceptionCls(commandname, message)
nest.ll_api.BadDelay: ('BadDelay in Connect_g_g_D_D: Delay value 0 is invalid: Delay must be greater than or equal to resolution', 'BadDelay', <SLILiteral: Connect_g_g_D_D>, ': Delay value 0 is invalid: Delay must be greater than or equal to resolution')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/mnist_keras_nest.py", line 153, in <module>
    main(config_filepath)
  File "/home/dizcza/PycharmProjects/other/snn_toolbox/snntoolbox/bin/run.py", line 31, in main
    run_pipeline(config)
  File "/home/dizcza/PycharmProjects/other/snn_toolbox/snntoolbox/bin/utils.py", line 129, in run_pipeline
    spiking_model.build(parsed_model, **testset)
  File "/home/dizcza/PycharmProjects/other/snn_toolbox/snntoolbox/simulation/utils.py", line 441, in build
    self.build_convolution(layer)
  File "/home/dizcza/PycharmProjects/other/snn_toolbox/snntoolbox/simulation/target_simulators/pyNN_target_sim.py", line 155, in build_convolution
    self.sim.FromListConnector(connections, ['weight', 'delay'])))
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/PyNN-0.9.5.dev0-py3.7.egg/pyNN/nest/projections.py", line 59, in __init__
    connector.connect(self)
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/PyNN-0.9.5.dev0-py3.7.egg/pyNN/connectors.py", line 546, in connect
    projection._convergent_connect(sources, tgt, **connection_parameters)
  File "/home/dizcza/anaconda3/envs/snn_toolbox-conda/lib/python3.7/site-packages/PyNN-0.9.5.dev0-py3.7.egg/pyNN/nest/projections.py", line 178, in _convergent_connect
    raise errors.ConnectionError(errmsg)
pyNN.errors.ConnectionError: ('BadDelay in Connect_g_g_D_D: Delay value 0 is invalid: Delay must be greater than or equal to resolution', 'BadDelay', <SLILiteral: Connect_g_g_D_D>, ': Delay value 0 is invalid: Delay must be greater than or equal to resolution'). presynaptic_cells=[787 903 902 901 900 899 875 873 872 871 847 846 874 844 845 789 790 791
 815 788 817 818 819 843 816], postsynaptic_cell=1573, weights=[[  47.00486362 -149.68934655  -49.93713275   -2.76117749   46.6363579
    90.42757004 -149.20666814   90.95539153  100.26297718  106.19264096
  -122.27715552  -64.65259939  -29.49396148   90.83072841   32.23535791
   122.6894781    63.53992224  -83.09756219   21.30669169   22.91868255
    61.9224906   -60.5805926   -85.03986895   82.16306567   42.93421656]], delays=[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]], synapse model='static_synapse_lbl'
```

I fixed with `config['cell']['delay'] = 1` but I'm not sure if I'm doing right here. Because when I run the example, it works but always outputs 0% accuracy, 100% error, no spikes... In the end, it printed
```
Total accuracy: 0.00% on 5 test samples.
Accuracy averaged by class size: 50.00%
```

**Comment by rbodo** [comment]
Try reducing the simulation time step and increasing the duration:

```
[simulation]
dt = 0.1
duration = 200
```

Likewise set the delay and refractory period to 0.1.

If that does not help, it's probably an incompatibility with the new Nest version. I will not be able to look at this until end of January. Your other option in that case is to roll back your Nest version.

Please let me know what you get.

**Comment by dizcza** [comment]
Which version of NEST did you test?

**Comment by rbodo** [comment]
2.14.0

**Comment by dizcza** [comment]
And what is pyNN version? I get different errors, depending on which pyNN I use with NEST 2.14.

**Comment by rbodo** [comment]
Don't know, sorry. Have no way of checking it right now and it's been too long ago to remember. 

I take it decreasing the time resolution / increasing the duration did not help?

**Comment by dizcza** [comment]
Yes, it didn't help - still 0% accuracy.

**Comment by meltingCat** [comment]
@dizcza where did you add `config['cell']['delay']` = 1 ?

**Comment by dizcza** [comment]
@meltingCat 
I followed these instructions

> Based on the error message, please add the following to the config dict:
> 
> ```
> config['cell'] = {
>     'tau_refrac': 1               # Refractory period must be at least one time step.
> }
> ```

in `mnist_keras_nest.py`

**Comment by rbodo** [comment]
OK, finally got a chance to run it myself. The trick is to simply lower the threshold to get more spikes. (There is even a message to that effect printed somewhere in the toolbox output, but it can admittedly be a bit buried...)
I updated the Nest example with working parameters.
