### ISSUE TITLE
cannot convert ANN to SNN with Pytorch input model

### ISSUE THREAD

**Issue by minhson** [NeuromorphicProcessorProject/snn_toolbox#65]
i tried to convert ANN to SNN with Pytorch model input. However, i got the error as below:
```
Initializing INI simulator...

Loading data set from '.npz' files in /home/sonlm/workplace/snn_toolbox/temp/vgg9_bn.

WARNING: Ignored mismatch when loading pytorch state_dict.
Error(s) in loading state_dict for Model:
	Missing key(s) in state_dict: "features.0.weight", "features.1.weight", "features.1.bias", "features.1.running_mean", "features.1.running_var", "features.3.weight", "features.4.weight", "features.4.bias", "features.4.running_mean", "features.4.running_var", "features.7.weight", "features.8.weight", "features.8.bias", "features.8.running_mean", "features.8.running_var", "features.10.weight", "features.11.weight", "features.11.bias", "features.11.running_mean", "features.11.running_var", "features.14.weight", "features.15.weight", "features.15.bias", "features.15.running_mean", "features.15.running_var", "features.17.weight", "features.18.weight", "features.18.bias", "features.18.running_mean", "features.18.running_var". 
	Unexpected key(s) in state_dict: "features.module.0.weight", "features.module.1.weight", "features.module.1.bias", "features.module.1.running_mean", "features.module.1.running_var", "features.module.1.num_batches_tracked", "features.module.3.weight", "features.module.4.weight", "features.module.4.bias", "features.module.4.running_mean", "features.module.4.running_var", "features.module.4.num_batches_tracked", "features.module.7.weight", "features.module.8.weight", "features.module.8.bias", "features.module.8.running_mean", "features.module.8.running_var", "features.module.8.num_batches_tracked", "features.module.10.weight", "features.module.11.weight", "features.module.11.bias", "features.module.11.running_mean", "features.module.11.running_var", "features.module.11.num_batches_tracked", "features.module.14.weight", "features.module.15.weight", "features.module.15.bias", "features.module.15.running_mean", "features.module.15.running_var", "features.module.15.num_batches_tracked", "features.module.17.weight", "features.module.18.weight", "features.module.18.bias", "features.module.18.running_mean", "features.module.18.running_var", "features.module.18.num_batches_tracked". 
Traceback (most recent call last):
  File "cifar10_pytorch_INI.py", line 181, in <module>
    main(config_filepath)
  File "/home/sonlm/.local/lib/python3.6/site-packages/snntoolbox/bin/run.py", line 31, in main
    run_pipeline(config)
  File "/home/sonlm/.local/lib/python3.6/site-packages/snntoolbox/bin/utils.py", line 73, in run_pipeline
    config.get('paths', 'filename_ann'))
  File "/home/sonlm/.local/lib/python3.6/site-packages/snntoolbox/parsing/model_libs/pytorch_input_lib.py", line 81, in load
    input_shape = [1] + list(model_pytorch.input_shape)
  File "/home/sonlm/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'Model' object has no attribute 'input_shape'
```

**ANN model**: VGG9 
**Pytorch model script**:
```
class Model(nn.Module):
     def __init__(self):
         super(Model, self).__init__()
         self.features = nn.Sequential(
                 nn.Conv2d(3, 128, kernel_size=3, padding=1, bias=False),
                 nn.BatchNorm2d(128, momentum=0.9, eps=1e-4),
                 nn.ReLU(inplace=True),
                 nn.Conv2d(128, 128, kernel_size=3, padding=1, bias=False),
                 nn.BatchNorm2d(128, momentum=0.9, eps=1e-4),
                 nn.ReLU(inplace=True),
                 nn.MaxPool2d(kernel_size=2, stride=2),
                 nn.Conv2d(128, 256, kernel_size=3, padding=1, bias=False),
                 nn.BatchNorm2d(256, momentum=0.9, eps=1e-4),
                 nn.ReLU(inplace=True),
                 nn.Conv2d(256, 256, kernel_size=3, padding=1, bias=False),
                 nn.BatchNorm2d(256, momentum=0.9, eps=1e-4),
                 nn.ReLU(inplace=True),
                 nn.MaxPool2d(kernel_size=2, stride=2),
                 nn.Conv2d(256, 512, kernel_size=3, padding=1, bias=False),
                 nn.BatchNorm2d(512, momentum=0.9, eps=1e-4),
                 nn.ReLU(inplace=True),
                 nn.Conv2d(512, 512, kernel_size=3, padding=1, bias=False),
                 nn.BatchNorm2d(512, momentum=0.9, eps=1e-4),
                 nn.ReLU(inplace=True),
                 nn.MaxPool2d(kernel_size=2, stride=2)
                 )
         self.classifier = nn.Sequential(
                 nn.Linear(512 * 4 * 4, 1024, bias=False),
                 nn.BatchNorm1d(1024, momentum=0.9, eps=1e-4),
                 nn.ReLU(inplace=True),
                 #nn.Dropout(0.5),
                 nn.Linear(1024, 1024, bias=False),
                 nn.BatchNorm1d(1024, momentum=0.9, eps=1e-4),
                 nn.ReLU(inplace=True),
                 #nn.Dropout(0.5),
                 nn.Linear(1024, 10, bias=False),
                 nn.BatchNorm1d(10, affine=False, momentum=0.9, eps=1e-4),
                 nn.LogSoftmax(dim=1)
                 )
         # Initialize weights
         for m in self.modules():
             if isinstance(m, nn.Conv2d):
                 n = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
                 m.weight.data.normal_(0, math.sqrt(2. / n))
                 #FIXMEm.bias.data.zero_()
 
     def forward(self, x):
         x = self.features(x)
         x = x.view(x.size(0), -1)
         x = self.classifier(x)
         return x
```
i trained this model with Cifar10 dataset in Pytorch and save model parameters to *.pkl file with this line of code:
```
filename = os.path.join(save_path, 'model_best.pkl')
torch.save(model.state_dict(), filename)
```
Could you help me with this?
Thanks you in advance!

**Comment by rbodo** [comment]
Apologies, this is an undocumented hack. Pytorch support is still in its infancy.

In your pytorch model script, please give the Model class an input_shape attribute like so:

```
class Model(nn.Module):
     def __init__(self):
         super(Model, self).__init__()
         self.input_shape = [3, 128, 128]  # This is new
         self.features = nn.Sequential(
         ...
```

Also, you can see from the warning that the pytorch state_dict couldn't be loaded completely because your variables are called `features.module.0.weight` etc but the toolbox expects `features.0.weight`. A simple fix is to rename the keys in your state_dict:

```
new_state_dict = {}
for k, v in state_dict.items():
    k = k.replace('module.', '')
    new_state_dict[k] = v
```

If you'd like to submit a more sustainable solution, a pull-request would be very welcome.

**Comment by minhson** [comment]
Thanks you!
I used your advice and the conversion from Pytorch to ONNX was successful. However, the conversion from ONNX to Keras was failed due to this error as below:
```
Traceback (most recent call last):
  File "cifar10_pytorch_INI.py", line 182, in <module>
    main(config_filepath)
  File "/home/sonlm/.local/lib/python3.6/site-packages/snntoolbox/bin/run.py", line 31, in main
    run_pipeline(config)
  File "/home/sonlm/.local/lib/python3.6/site-packages/snntoolbox/bin/utils.py", line 73, in run_pipeline
    config.get('paths', 'filename_ann'))
  File "/home/sonlm/.local/lib/python3.6/site-packages/snntoolbox/parsing/model_libs/pytorch_input_lib.py", line 108, in load
    model_keras = pytorch_to_keras(model_pytorch, input_torch, [(3, 32, 32,)], verbose=True, change_ordering=change_ordering)
  File "/home/sonlm/.local/lib/python3.6/site-packages/pytorch2keras/converter.py", line 83, in pytorch_to_keras
    verbose=verbose, change_ordering=change_ordering)
  File "/home/sonlm/.local/lib/python3.6/site-packages/onnx2keras/converter.py", line 251, in onnx_to_keras
    model_tf_ordering = keras.models.Model.from_config(conf)
  File "/home/sonlm/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 987, in from_config
    config, custom_objects)
  File "/home/sonlm/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 2029, in reconstruct_from_config
    process_node(layer, node_data)
  File "/home/sonlm/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py", line 1977, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "/home/sonlm/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 897, in __call__
    self._maybe_build(inputs)
  File "/home/sonlm/.local/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/home/sonlm/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/normalization.py", line 327, in build
    raise ValueError('Invalid axis: %d' % x)
ValueError: Invalid axis: 3
```
I think this error happened due to the image data format of Pytorch and Keras.
Could you help me with this?

**Comment by rbodo** [comment]
No, I think this error is because of the one-dimensional BatchNorm layer in the classifier. Tensorflow complains that the axis is set to 3 (corresponding to the channel dimension), which is more axes than the Dense layer has. It seems ONNX does not convert the axis parameter of 1D BatchNorm layers correctly. 

I cannot debug this further as it seems to be an ONNX issue.

**Comment by minhson** [comment]
Thanks you!
Maybe i should use Keras model directly to avoid the errors like that.

**Comment by Naitik1502** [comment]
@minhson I am also trying to convert a pytorch model. Could you please share your config file as I am having trouble filling it. 
Thanks in advance!!

**Comment by rbodo** [comment]
Please see [this example script](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/master/examples/mnist_pytorch_INI.py).
