### ISSUE TITLE
Pytorch code to Loihi

### ISSUE THREAD

**Issue by albertopolito** [NeuromorphicProcessorProject/snn_toolbox#73]
Good morning,
can I convert, with your tool, pytorch code in order to run this on the Loihi machine?
I make this question because in the examples there is only the conversion from Pytorch to the INI simulator. 
Thanks a lot for your time, 
Best regards.

**Comment by rbodo** [comment]
Yes, that should be possible. The toolbox is built such that the backend simulator / hardware is independent of the frontend model.

**Comment by albertopolito** [comment]
Thanks for your answer. 
So, to do an example of Pytorch to Loihi code, I can take the code mnist_keras_loihi.py and replace the ANN description with the pytorch model without changing anything else?
Thanks in advance for your support.

**Comment by rbodo** [comment]
I think it would be easier to go the other direction. Start with the [pytorch example](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/master/examples/mnist_pytorch_INI.py) and change the config file to match the Loihi example. I.e. copy over the [loihi] section, and set 'simulator': 'loihi'.

**Comment by albertopolito** [comment]
Thanks for the answer. 
In particular I would use your conversion tool to implement on Loihi the SNN described at this link: [https://github.com/yjwu17/BP-for-SpikingNN](url) . 
My question is: to mimic the behavior of an SNN it uses a custom activation function and forward algorithm; I don't know if they are supported.
Thanks in advance for your support.

**Comment by rbodo** [comment]
The toolbox transforms a PyTorch model to ONNX and then to Keras using the onnx2keras library. 

I don't think ONNX / onnx2keras will be able to handle a custom PyTorch activation function correctly. Might be easiest to create the model from scratch in PyTorch or directly in Keras using standard operators, and then transfer the weights from your BP-for-SNN model.

**Comment by albertopolito** [comment]
Thanks for your answer.
I have some problem with the use of your example mnist_keras_loihi.py on the ncl-edu server. 
I have the nsdk version: 0.9.5 installed in the virtual environment. To install it is requested the python version 3.5.2. 
But your toolbox request python 3.6, in particular for tensorflow and keras packages. 
So in the same virtual environment I have python 3.5.2 as default and I use python 3.6.9 to install the toolbox. 
I run the example with python 3.6.9 but it take me the error: no module named 'nsdk_modules_ncl' .
I run the same example with python 3.5.2 but it take me the error: no module named 'tensorflow.keras' 
How I can overcome this problem?

**Comment by rbodo** [comment]
You should be able to solve the `no module named 'nxsdk_modules_ncl'` error by adding the installation directory (where `nxsdk_modules_ncl` lives) to PYTHONPATH, as done [here](https://github.com/NeuromorphicProcessorProject/snn_toolbox/blob/bb001707b56f024f4039556a67352ee74d0e147a/examples/mnist_keras_loihi.py#L30).

**Comment by albertopolito** [comment]
It doesn't work.
I use another virtual environment and another release of nxsdk (0.9.9), and install it with python 3.6.9 that is the default python of this venv. I reinstall all in this new venv and replace the line of code of the PYTHONPATH with the directory where there are the nxsdk modules.

The error is:

 Traceback (most recent call last):
  File "./examples/mnist_keras_loihi.py", line 161, in <module>
    main(config_filepath)
  File "/homes/albertoviale/python3_6_venv/lib/python3.6/site-packages/snntoolbox/bin/run.py", line 31, in main
    run_pipeline(config)
  File "/homes/albertoviale/python3_6_venv/lib/python3.6/site-packages/snntoolbox/bin/utils.py", line 56, in run_pipeline
    target_sim = import_target_sim(config)
  File "/homes/albertoviale/python3_6_venv/lib/python3.6/site-packages/snntoolbox/bin/utils.py", line 244, in import_target_sim
    + sim_str + code_str + '_target_sim')
  File "/homes/albertoviale/.local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/homes/albertoviale/python3_6_venv/lib/python3.6/site-packages/snntoolbox/simulation/target_simulators/loihi_target_sim.py", line 10, in <module>
    from nxsdk_modules_ncl.snntoolbox.nx_backend import SNN
ModuleNotFoundError: No module named 'nxsdk_modules_ncl'

**Comment by rbodo** [comment]
Note that nxsdk_modules_ncl is not the same as nxsdk_modules. The latter is part of the main nxsdk package; the former is outsourced [here](https://github.com/intel-nrc-ecosystem/models).

**Comment by albertopolito** [comment]
Thanks for your answer.

Ok, now this part work, but it doesn't recognize another module. 
The error is:

Traceback (most recent call last):
  File "../snn_toolbox/examples/mnist_keras_loihi.py", line 161, in <module>
    main(config_filepath)
  File "/homes/albertoviale/python3_6_venv/lib/python3.6/site-packages/snntoolbox/bin/run.py", line 31, in main
    run_pipeline(config)
  File "/homes/albertoviale/python3_6_venv/lib/python3.6/site-packages/snntoolbox/bin/utils.py", line 56, in run_pipeline
    target_sim = import_target_sim(config)
  File "/homes/albertoviale/python3_6_venv/lib/python3.6/site-packages/snntoolbox/bin/utils.py", line 244, in import_target_sim
    + sim_str + code_str + '_target_sim')
  File "/homes/albertoviale/.local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/homes/albertoviale/python3_6_venv/lib/python3.6/site-packages/snntoolbox/simulation/target_simulators/loihi_target_sim.py", line 10, in <module>
    from nxsdk_modules_ncl.snntoolbox.nx_backend import SNN
  File "/homes/albertoviale/models/nxsdk_modules_ncl/snntoolbox/nx_backend.py", line 31, in <module>
    import nxsdk_modules_ncl.dnn.src.dnn_layers as nxtf
  File "/homes/albertoviale/models/nxsdk_modules_ncl/dnn/__init__.py", line 15, in <module>
    from nxsdk_modules_ncl.dnn.src.dnn_layers import \
  File "/homes/albertoviale/models/nxsdk_modules_ncl/dnn/src/dnn_layers.py", line 36, in <module>
    from nxsdk_modules_ncl.dnn.src.plotting import plot_multiplicity, \
  File "/homes/albertoviale/models/nxsdk_modules_ncl/dnn/src/plotting.py", line 23, in <module>
    from matplotlib.ticker import IndexLocator, AutoMinorLocator
  File "/homes/albertoviale/python3_6_venv/lib/python3.6/site-packages/matplotlib/__init__.py", line 127, in <module>
    from . import cbook
  File "/homes/albertoviale/python3_6_venv/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 13, in <module>
    import bz2
  File "/homes/albertoviale/.local/lib/python3.6/bz2.py", line 23, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'

I see on the net that this can be caused by the local installation of python. But I'm a begginer and I don't know how to overcome this problem.

**Comment by rbodo** [comment]
Sorry, I can't help you with this.
