### ISSUE TITLE
example/mnist_keras_nest.py

### ISSUE THREAD

**Issue by CHonChou** [NeuromorphicProcessorProject/snn_toolbox#76]
When I run example/mnist_keras_nest.py, an error occurred:
Traceback (most recent call last):
  File "/home/kugatsu/my_py_project/ann2snn/snn_toolbox-master/examples/mnist_keras_nest.py", line 157, in <module>
    main(config_filepath)
  File "/home/kugatsu/anaconda3/envs/tf2/lib/python3.7/site-packages/snntoolbox/bin/run.py", line 31, in main
    run_pipeline(config)
  File "/home/kugatsu/anaconda3/envs/tf2/lib/python3.7/site-packages/snntoolbox/bin/utils.py", line 145, in run_pipeline
    results = run(spiking_model, **testset)
  File "/home/kugatsu/anaconda3/envs/tf2/lib/python3.7/site-packages/snntoolbox/bin/utils.py", line 220, in wrapper
    results.append(run_single(snn, **testset))
  File "/home/kugatsu/anaconda3/envs/tf2/lib/python3.7/site-packages/snntoolbox/bin/utils.py", line 142, in run
    return snn.run(**test_set)
  File "/home/kugatsu/anaconda3/envs/tf2/lib/python3.7/site-packages/snntoolbox/simulation/utils.py", line 607, in run
    output_b_l_t = self.simulate(**data_batch_kwargs)
  File "/home/kugatsu/anaconda3/envs/tf2/lib/python3.7/site-packages/snntoolbox/simulation/target_simulators/pyNN_target_sim.py", line 207, in simulate
    for amplitude in x_flat]
  File "/home/kugatsu/anaconda3/envs/tf2/lib/python3.7/site-packages/snntoolbox/simulation/target_simulators/pyNN_target_sim.py", line 207, in <listcomp>
    for amplitude in x_flat]
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/kugatsu/anaconda3/envs/tf2/lib/python3.7/site-packages/numpy/core/function_base.py", line 113, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by rbodo** [comment]
`self._duration * amplitude` --> `int(self._duration * amplitude)`

This input mode is experimental. To use Poisson input, add the following to your config:

`config['input'] = {'poisson_input': True}`
