### ISSUE TITLE
Tensorflow: OperatorNotAllowedInGraphError

### ISSUE THREAD

**Issue by Narduzzi** [NeuromorphicProcessorProject/snn_toolbox#89]
Hello @rbodo,

I am using the development version of the toolbox.
TF version: 2.4.1

When converting the model after the computation of the average spike rate, the following error occurs:

```
Traceback (most recent call last):
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 447, in converted_call
    converted_f = _convert_actual(target_entity, program_ctx)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 284, in _convert_actual
    transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 286, in transform
    return self.transform_function(obj, user_context)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 470, in transform_function
    nodes, ctx = super(PyToPy, self).transform_function(fn, user_context)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 363, in transform_function
    result = self.transform_ast(node, context)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 252, in transform_ast
    node = self.initial_analysis(node, ctx)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 240, in initial_analysis
    node = activity.resolve(node, ctx, None)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 709, in resolve
    return ActivityAnalyzer(context, parent_scope).visit(node)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/transformer.py", line 445, in visit
    result = super(Base, self).visit(node)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/ast.py", line 271, in visit
    return visitor(node)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 579, in visit_FunctionDef
    node = self._visit_arg_annotations(node)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 555, in _visit_arg_annotations
    node = self._visit_arg_declarations(node)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/pyct/static_analysis/activity.py", line 560, in _visit_arg_declarations
    node.args.posonlyargs = self._visit_node_list(node.args.posonlyargs)
AttributeError: 'arguments' object has no attribute 'posonlyargs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nar/Documents/Projects/SNNTB/pytests/test_distirbutedGPU.py", line 80, in <module>
    evaluator.evaluate(m)
  File "/Users/nar/Documents/Projects/SNNTB/evaluators/SNNTBEvaluator.py", line 214, in evaluate
    main(config_filepath)
  File "/Users/nar/Documents/Projects/snn_toolbox/snntoolbox/bin/run.py", line 31, in main
    run_pipeline(config)
  File "/Users/nar/Documents/Projects/snn_toolbox/snntoolbox/bin/utils.py", line 145, in run_pipeline
    results = run(spiking_model, **testset)
  File "/Users/nar/Documents/Projects/snn_toolbox/snntoolbox/bin/utils.py", line 220, in wrapper
    results.append(run_single(snn, **testset))
  File "/Users/nar/Documents/Projects/snn_toolbox/snntoolbox/bin/utils.py", line 142, in run
    return snn.run(**test_set)
  File "/Users/nar/Documents/Projects/snn_toolbox/snntoolbox/simulation/utils.py", line 737, in run
    self.reset(batch_idx)
  File "/Users/nar/Documents/Projects/snn_toolbox/snntoolbox/simulation/target_simulators/INI_temporal_mean_rate_target_sim.py", line 244, in reset
    layer.reset(sample_idx)
  File "/Users/nar/Documents/Projects/snn_toolbox/snntoolbox/simulation/backends/inisim/temporal_mean_rate_tensorflow.py", line 92, in reset
    self.reset_spikevars(tf.constant(sample_idx))
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 828, in __call__
    result = self._call(*args, **kwds)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 871, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 726, in _initialize
    *args, **kwds))
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3206, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3887, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    user_requested=True,
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 454, in converted_call
    return _fall_back_unconverted(f, args, kwargs, options, e)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 501, in _fall_back_unconverted
    return _call_unconverted(f, args, kwargs, options)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 475, in _call_unconverted
    return f.__self__.call(args, kwargs)
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3849, in call
    return wrapped_fn(self.weakrefself_target__(), *args, **kwargs)
  File "/Users/nar/Documents/Projects/snn_toolbox/snntoolbox/simulation/backends/inisim/temporal_mean_rate_tensorflow.py", line 360, in reset_spikevars
    if do_reset:
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 885, in __bool__
    self._disallow_bool_casting()
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 489, in _disallow_bool_casting
    "using a `tf.Tensor` as a Python `bool`")
  File "/Users/nar/opt/anaconda3/envs/snn_env/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 476, in _disallow_when_autograph_enabled
    " indicate you are trying to use an unsupported feature.".format(task))
tensorflow.python.framework.errors_impl.OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.
```

Any idea of what could be the source of the bug?

**Comment by rbodo** [comment]
Hi Narduzzi,

I'm not able to reproduce the issue (using TF 2.5.0). Maybe try updating TF. Are you able to run the example script mnist_keras_INI.py?

**Comment by Narduzzi** [comment]
Hello @rbodo ,

Upgrading to TF2.5.0rc0 seems to have solved the problem. 
Thank you for the help!

PS: maybe the requirements.txt file could explicitly mention this version of TF.
